export const spacesData = [
  {
    id: 1,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-1.jpg",
    date: "2024",
    name: "Alice Christy Apartment",
    location: "Kerala, India",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "Alice Christy",
    route: "/sample-space",
  },
  {
    id: 2,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-2.jpg",
    date: "2024",
    name: "Anas Babu Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-2.jpeg",
    clientName: "Anas Babu",
    route: "/sample-space",
  },
  {
    id: 3,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-3.jpg",
    date: "2024",
    name: "Divya Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-3.jpeg",
    clientName: "Divya",
    route: "/sample-space",
  },
  {
    id: 4,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-4.jpg",
    date: "2024",
    name: "Francis Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-4.jpeg",
    clientName: "Francis",
    route: "/sample-space",
  },
  {
    id: 5,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-5.jpg",
    date: "2024",
    name: "John Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-5.jpeg",
    clientName: "John",
    route: "/sample-space",
  },
  {
    id: 6,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-6.jpg",
    date: "2024",
    name: "Jose Residence",
    location: "Mumbai, India",
    clientImage: "/spaces/client-6.jpeg",
    clientName: "Jose",
    route: "/sample-space",
  },
  {
    id: 7,
    categories: ["Commercial", "Healthcare"],
    image: "/spaces/space-7.jpg",
    date: "2024",
    name: "Gilead Care Home",
    location: "Kerala, India",
    clientImage: "/spaces/client-7.jpeg",
    clientName: "Gilead Care",
    route: "/sample-space",
  },
  {
    id: 8,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-8.jpg",
    date: "2024",
    name: "Bava's Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "Bava",
    route: "/sample-space",
  },
  {
    id: 9,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-9.jpg",
    date: "2024",
    name: "Thali Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-2.jpeg",
    clientName: "Thali",
    route: "/sample-space",
  },
  {
    id: 10,
    categories: ["Residential", "Exterior"],
    image: "/spaces/space-10.jpg",
    date: "2024",
    name: "Poornima Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-3.jpeg",
    clientName: "Poornima",
    route: "/sample-space",
  },
  {
    id: 11,
    categories: ["Residential", "Exterior"],
    image: "/spaces/space-11.jpg",
    date: "2024",
    name: "Ajith Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-4.jpeg",
    clientName: "Ajith",
    route: "/sample-space",
  },
  {
    id: 12,
    categories: ["Residential", "Exterior"],
    image: "/spaces/space-12.jpg",
    date: "2024",
    name: "Chrisbin Sony Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-5.jpeg",
    clientName: "Chrisbin Sony",
    route: "/sample-space",
  },
  {
    id: 13,
    categories: ["Residential", "Exterior"],
    image: "/spaces/space-13.jpg",
    date: "2024",
    name: "Sreelatha Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-6.jpeg",
    clientName: "Sreelatha",
    route: "/sample-space",
  },
  {
    id: 14,
    categories: ["Commercial", "Retail"],
    image: "/spaces/space-14.jpg",
    date: "2024",
    name: "Royal Supermarket",
    location: "Chelakkara, India",
    clientImage: "/spaces/client-7.jpeg",
    clientName: "Royal Group",
    route: "/sample-space",
  },
  {
    id: 15,
    categories: ["Commercial", "Hospitality"],
    image: "/spaces/space-15.jpg",
    date: "2024",
    name: "Proposed Cafe",
    location: "Chelakkara, India",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "Cafe Group",
    route: "/sample-space",
  },
];
