export const spacesData = [
  {
    id: 1,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-1.jpg",
    date: "2024",
    name: "Alice Christy Apartment",
    location: "Kerala, India",
    clientImage: "/spaces/client-1.jpeg",
    clientName: "Alice Christy",
    route: "/sample-space",
  },
  {
    id: 2,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-2.jpg",
    date: "2024",
    name: "Anas Babu Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-2.jpeg",
    clientName: "Anas Babu",
    route: "/sample-space",
  },
  {
    id: 3,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-3.jpg",
    date: "2024",
    name: "Divya Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-3.jpeg",
    clientName: "Divya",
    route: "/sample-space",
  },
  {
    id: 4,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-4.jpg",
    date: "2024",
    name: "Francis Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-4.jpeg",
    clientName: "Francis",
    route: "/sample-space",
  },
  {
    id: 5,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-5.jpg",
    date: "2024",
    name: "John Residence",
    location: "Kerala, India",
    clientImage: "/spaces/client-5.jpeg",
    clientName: "John",
    route: "/sample-space",
  },
  {
    id: 6,
    categories: ["Residential", "Interior"],
    image: "/spaces/space-6.jpg",
    date: "2024",
    name: "Jose Residence",
    location: "Mumbai, India",
    clientImage: "/spaces/client-6.jpeg",
    clientName: "Jose",
    route: "/sample-space",
  },
  {
    id: 7,
    categories: ["Commercial", "Exterior"],
    image: "/spaces/space-7.jpg",
    date: "2024",
    name: "Gilead Care Home",
    location: "Kerala, India",
    clientImage: "/spaces/client-7.jpeg",
    clientName: "Gilead Care",
    route: "/sample-space",
  },
];
