const items = [
  "Alice Christy Apartment - View 1",
  "Alice Christy Apartment - View 2",
  "Alice Christy Apartment - View 3",
  "Alice Christy Apartment - View 4",
  "Alice Christy Apartment - View 5",
  "Alice Christy Apartment - View 6",
  "Alice Christy Apartment - View 7",
  "Alice Christy Apartment - View 8",
  "Alice Christy Apartment - View 9",
  "Alice Christy Apartment - View 10",
  "Alice Christy Apartment - View 11",
  "Anas Babu Residence - Interior 1",
  "Anas Babu Residence - Interior 2",
  "Anas Babu Residence - Interior 3",
  "Anas Babu Residence - Interior 4",
  "Anas Babu Residence - Interior 5",
  "Anas Babu Residence - Interior 6",
  "Divya Residence - Design 1",
  "Divya Residence - Design 2",
  "Divya Residence - Design 3",
  "Divya Residence - Design 4",
  "Divya Residence - Design 5",
  "Divya Residence - Design 6",
  "Francis Residence - Bedroom 1",
  "Francis Residence - Bedroom 2",
  "Francis Residence - Bedroom 3",
  "Francis Residence - Bedroom 4",
  "Francis Residence - Bedroom Bath 1",
  "Francis Residence - Bedroom Bath 2",
  "Francis Residence - Bedroom Bath 3",
  "Francis Residence - Bedroom Bath 4",
  "Francis Residence - Living Space 1",
  "Francis Residence - Living Space 2",
  "Francis Residence - Kitchen 1",
  "Francis Residence - Kitchen 2",
  "Francis Residence - Kitchen 3",
  "Francis Residence - Kitchen 4",
  "Francis Residence - Master Bedroom 1",
  "Francis Residence - Master Bedroom 2",
  "Francis Residence - Master Bedroom 3",
  "Francis Residence - Master Bath 1",
  "Francis Residence - Master Bath 2",
  "Ajith Residence - Exterior 1",
  "Ajith Residence - Exterior 2",
  "Ajith Residence - Exterior 3",
  "Ajith Residence - Exterior 4",
  "Royal Supermarket Chelakkara 1",
  "Royal Supermarket Chelakkara 2",
  "Gilead Care Home - Exterior 1",
  "Gilead Care Home - Exterior 2",
  "Gilead Care Home - Exterior 3",
  "Gilead Care Home - Exterior 4",
  "Gilead Care Home - Exterior 5",
  "Gilead Care Home - Exterior 6",
  "Poornima Residence - Exterior 1",
  "Poornima Residence - Exterior 2",
  "Poornima Residence - Exterior 3",
  "Poornima Residence - Exterior 4",
  "Poornima Residence - Exterior 5",
  "Proposed Cafe Chelakkara 1",
  "Proposed Cafe Chelakkara 2",
  "Proposed Cafe Chelakkara 3",
  "Chrisbin Sony Residence - Exterior 1",
  "Chrisbin Sony Residence - Exterior 2",
  "Chrisbin Sony Residence - Exterior 3",
  "Sreelatha Residence - Exterior 1",
  "Sreelatha Residence - Exterior 2",
  "Sreelatha Residence - Exterior 3",
  "Thali Residence - Exterior 1",
  "Thali Residence - Exterior 2",
  "Wadakanchery Church",
  "Bava's Residence - Bedroom A",
  "Bava's Residence - Bedroom B",
  "Bava's Residence - Bedroom C",
  "Bava's Residence - Bedroom D",
  "Bava's Residence - Dining Room 1",
  "Bava's Residence - Dining Room 2",
  "Bava's Residence - Family Living 1",
  "Bava's Residence - Family Living 2",
  "Bava's Residence - Living Room 1",
  "Bava's Residence - Living Room 2",
  "John Residence - Bedroom A",
  "John Residence - Bedroom B",
  "John Residence - Bedroom C",
  "John Residence - Dining Area 1",
  "John Residence - Dining Area 2",
  "John Residence - Living Space 1",
  "John Residence - Living Space 2",
  "John Residence - Living Space 3",
  "John Residence - Master Bedroom",
  "John Residence - Study Room",
  "Jose Residence Mumbai - Bedroom",
  "Jose Residence Mumbai - Dining 1",
  "Jose Residence Mumbai - Dining 2",
  "Jose Residence Mumbai - Living 1",
  "Jose Residence Mumbai - Living 2",
  "Joshy Residence - Living Area",
  "Poornima Residence - Interior 1",
  "Poornima Residence - Interior 2",
  "Poornima Residence - Interior 3",
  "Poornima Residence - Interior 4",
  "Architectural Blueprint 1",
  "Architectural Blueprint 2",
  "Architectural Blueprint 3",
  "Architectural Blueprint 4",
  "Architectural Blueprint 5",
  "Architectural Blueprint 6",
  "Architectural Blueprint 7",
  "Architectural Blueprint 8",
  "Architectural Blueprint 9",
  "Architectural Blueprint 10",
  "Architectural Blueprint 11",
  "Architectural Blueprint 12",
  "Architectural Blueprint 13",
  "Architectural Blueprint 14",
  "Architectural Blueprint 15",
];

export default items;
